/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fee.management.system;
import java.awt.Color;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.DriverManager;
import javax.xml.transform.Result;
import java.util.Date;
import javax.swing.JOptionPane;
import java.lang.*;
import java.text.SimpleDateFormat;
/**
 *
 * @author sathw
 */
public class printreceipt extends javax.swing.JFrame {

    /**
     * Creates new form printreceipt
     */
    public printreceipt() {
        initComponents();
        getRecords();
        Container c=getContentPane();
        c.setBackground(new Color(153,255,204));
    }
    public void getRecords()
    {
        try{
            Connection con=DBconnection.getConnection();
            PreparedStatement stmt=con.prepareStatement("select * from fees_details order by reciept_no desc limit 1");
            ResultSet rs=stmt.executeQuery();
            rs.next();
            
            txtreceiptno.setText(rs.getString("reciept_no"));
            txtpaymentmode.setText(rs.getString("payment_mode"));
            String Paymentmode=rs.getString("payment_mode");
            if(Paymentmode.equalsIgnoreCase("cheque")){
                txtchequeddno.setText(rs.getString("cheque_no"));
                txtbankname.setText(rs.getString("bank_name"));
            }
            if(Paymentmode.equalsIgnoreCase("Cash")){
                txtchequeddno.setText("---");
                txtbankname.setText("---");
            }
             if(Paymentmode.equalsIgnoreCase("Cash")){
                txtchequeddno.setText(rs.getString("dd_no"));
                txtbankname.setText(rs.getString("bank_name"));
            }
             
            txtreceivedfrom.setText(rs.getString("student_name"));
            txtdate.setText(rs.getString("date"));
            txtyear1.setText(rs.getString("year1"));
            txtyear2.setText(rs.getString("year2"));
            txtinitialamount.setText(rs.getString("amount"));
            txttax.setText(rs.getString("cgst"));
            txtgst.setText(rs.getString("sgst"));
            txttotal.setText(rs.getString("total_amount"));
            txttotalinwords.setText(rs.getString("total_in_words"));
            txtremark.setText(rs.getString("remark"));
            
            
            
            
        }
        catch(Exception e){
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsidebar = new javax.swing.JPanel();
        paneledit = new javax.swing.JPanel();
        btnedit = new javax.swing.JLabel();
        panelhome = new javax.swing.JPanel();
        btnhome = new javax.swing.JLabel();
        panelhome2 = new javax.swing.JPanel();
        btnhome2 = new javax.swing.JLabel();
        panelhome3 = new javax.swing.JPanel();
        btnhome3 = new javax.swing.JLabel();
        panelhome4 = new javax.swing.JPanel();
        btnhome4 = new javax.swing.JLabel();
        panelsearchrecord = new javax.swing.JPanel();
        btnsearchrecord = new javax.swing.JLabel();
        panelviewall = new javax.swing.JPanel();
        btnviewall = new javax.swing.JLabel();
        panellogout = new javax.swing.JPanel();
        btnlogout = new javax.swing.JLabel();
        panelback = new javax.swing.JPanel();
        btnback = new javax.swing.JLabel();
        panelhome1 = new javax.swing.JPanel();
        btnhome1 = new javax.swing.JLabel();
        panelhome5 = new javax.swing.JPanel();
        btnhome5 = new javax.swing.JLabel();
        panelhome6 = new javax.swing.JPanel();
        btnhome6 = new javax.swing.JLabel();
        panelhome7 = new javax.swing.JPanel();
        btnhome7 = new javax.swing.JLabel();
        panelhome8 = new javax.swing.JPanel();
        btnhome8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtreceiptno = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtpaymentmode = new javax.swing.JLabel();
        txtchequeddno = new javax.swing.JLabel();
        txtbankname = new javax.swing.JLabel();
        txtreceivedfrom = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblcdd = new javax.swing.JLabel();
        lblbankname = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtdate = new javax.swing.JLabel();
        txtyear1 = new javax.swing.JLabel();
        txtyear2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtgst = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtinitialamount = new javax.swing.JLabel();
        txttax = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txttotalinwords = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txtremark = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txttotal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsidebar.setBackground(new java.awt.Color(255, 255, 255));
        panelsidebar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 102, 255), null, null));
        panelsidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paneledit.setBackground(new java.awt.Color(153, 255, 255));
        paneledit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        paneledit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paneleditMouseEntered(evt);
            }
        });
        paneledit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnedit.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnedit.setText("        Edit Course");
        btnedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btneditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btneditMouseExited(evt);
            }
        });
        paneledit.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 170, -1));

        panelsidebar.add(paneledit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, 40));

        panelhome.setBackground(new java.awt.Color(153, 255, 255));
        panelhome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelhomeMouseEntered(evt);
            }
        });
        panelhome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnhome.setText("            Edit");
        btnhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhomeMouseExited(evt);
            }
        });
        panelhome.add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 170, -1));

        panelhome2.setBackground(new java.awt.Color(153, 255, 255));
        panelhome2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelhome2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelhome2MouseEntered(evt);
            }
        });
        panelhome2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnhome2.setText("            Home");
        btnhome2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhome2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome2MouseExited(evt);
            }
        });
        panelhome2.add(btnhome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 170, -1));

        panelhome.add(panelhome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 170, 40));

        panelhome3.setBackground(new java.awt.Color(153, 255, 255));
        panelhome3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelhome3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelhome3MouseEntered(evt);
            }
        });
        panelhome3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnhome3.setText("            Home");
        btnhome3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhome3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome3MouseExited(evt);
            }
        });
        panelhome3.add(btnhome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 170, -1));

        panelhome4.setBackground(new java.awt.Color(153, 255, 255));
        panelhome4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelhome4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelhome4MouseEntered(evt);
            }
        });
        panelhome4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnhome4.setText("            Home");
        btnhome4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhome4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome4MouseExited(evt);
            }
        });
        panelhome4.add(btnhome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 170, -1));

        panelhome3.add(panelhome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 170, 40));

        panelhome.add(panelhome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 170, 40));

        panelsidebar.add(panelhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 170, 40));

        panelsearchrecord.setBackground(new java.awt.Color(153, 255, 255));
        panelsearchrecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 204, 255), null, null));
        panelsearchrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelsearchrecordMouseEntered(evt);
            }
        });
        panelsearchrecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsearchrecord.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnsearchrecord.setText("      Search Record");
        btnsearchrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsearchrecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsearchrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsearchrecordMouseExited(evt);
            }
        });
        panelsearchrecord.add(btnsearchrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 170, -1));

        panelsidebar.add(panelsearchrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 170, 40));

        panelviewall.setBackground(new java.awt.Color(153, 255, 255));
        panelviewall.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelviewall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelviewallMouseEntered(evt);
            }
        });
        panelviewall.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnviewall.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnviewall.setText("   View All Records");
        btnviewall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnviewallMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnviewallMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnviewallMouseExited(evt);
            }
        });
        panelviewall.add(btnviewall, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 170, -1));

        panelsidebar.add(panelviewall, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 170, 40));

        panellogout.setBackground(new java.awt.Color(153, 255, 255));
        panellogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panellogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panellogoutMouseEntered(evt);
            }
        });
        panellogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnlogout.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnlogout.setText("          Logout ");
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlogoutMouseExited(evt);
            }
        });
        panellogout.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 170, -1));

        panelsidebar.add(panellogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 170, 40));

        panelback.setBackground(new java.awt.Color(153, 255, 255));
        panelback.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelbackMouseEntered(evt);
            }
        });
        panelback.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnback.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnback.setText("            Back");
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbackMouseExited(evt);
            }
        });
        panelback.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 170, -1));

        panelsidebar.add(panelback, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 170, 40));

        panelhome1.setBackground(new java.awt.Color(153, 255, 255));
        panelhome1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelhome1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelhome1MouseEntered(evt);
            }
        });
        panelhome1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnhome1.setText("            Home");
        btnhome1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhome1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome1MouseExited(evt);
            }
        });
        panelhome1.add(btnhome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 170, -1));

        panelsidebar.add(panelhome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, 40));

        panelhome5.setBackground(new java.awt.Color(153, 255, 255));
        panelhome5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelhome5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelhome5MouseEntered(evt);
            }
        });
        panelhome5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnhome5.setText("            Print");
        btnhome5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhome5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome5MouseExited(evt);
            }
        });
        panelhome5.add(btnhome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 170, -1));

        panelhome6.setBackground(new java.awt.Color(153, 255, 255));
        panelhome6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelhome6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelhome6MouseEntered(evt);
            }
        });
        panelhome6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnhome6.setText("            Home");
        btnhome6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhome6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome6MouseExited(evt);
            }
        });
        panelhome6.add(btnhome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 170, -1));

        panelhome5.add(panelhome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 170, 40));

        panelhome7.setBackground(new java.awt.Color(153, 255, 255));
        panelhome7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelhome7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelhome7MouseEntered(evt);
            }
        });
        panelhome7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnhome7.setText("            Home");
        btnhome7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhome7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome7MouseExited(evt);
            }
        });
        panelhome7.add(btnhome7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 170, -1));

        panelhome8.setBackground(new java.awt.Color(153, 255, 255));
        panelhome8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelhome8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelhome8MouseEntered(evt);
            }
        });
        panelhome8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnhome8.setText("            Home");
        btnhome8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhome8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome8MouseExited(evt);
            }
        });
        panelhome8.add(btnhome8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 170, -1));

        panelhome7.add(panelhome8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 170, 40));

        panelhome5.add(panelhome7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 170, 40));

        panelsidebar.add(panelhome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 170, 40));

        getContentPane().add(panelsidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 640));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("UGC-AUTONOMOUS");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 255));
        jLabel11.setText("Dundigal,Medchal(M),Hyderabad,Telangana,India-500043");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 51));
        jLabel9.setText("Institute Of Technology And Management");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Marri Laxman Reddy");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 590, 20));

        txtreceiptno.setText("13232");
        jPanel1.add(txtreceiptno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 100, 20));

        jLabel2.setText("-");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 10, 20));

        jLabel3.setText("Receipt No:         MLR- ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 20));

        txtpaymentmode.setText("Payment Mode:  ");
        jPanel1.add(txtpaymentmode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, 20));

        txtchequeddno.setText("Cheque_id : ");
        jPanel1.add(txtchequeddno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, 20));

        txtbankname.setText("Bank name :");
        jPanel1.add(txtbankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, 20));

        txtreceivedfrom.setText("Received From:");
        jPanel1.add(txtreceivedfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, 20));

        jLabel8.setText("Payment Mode:  ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 20));

        lblcdd.setText("Cheque/DD no.: ");
        jPanel1.add(lblcdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 20));

        lblbankname.setText("Bank name :");
        jPanel1.add(lblbankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 20));

        jLabel15.setText("Received From:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 20));

        jLabel16.setText("The following payments in the college office for the year :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 20));

        txtdate.setText("Date:");
        jPanel1.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        txtyear1.setText("2021");
        jPanel1.add(txtyear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, 20));

        txtyear2.setText("2022");
        jPanel1.add(txtyear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, 20));

        jLabel19.setText("Date:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 210, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 590, 10));

        jLabel1.setText("Amount(in rs)");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, -1, -1));

        jLabel6.setText("S.No:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel7.setText("Head");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        jLabel18.setText("1");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        txtgst.setText("GST");
        jPanel1.add(txtgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 90, -1));

        jLabel21.setText("1");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 30, -1));

        jLabel22.setText("Tax(9%)");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 60, -1));

        jLabel23.setText("GST(9%)");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 60, -1));

        txtinitialamount.setText("GST");
        jPanel1.add(txtinitialamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 80, -1));

        txttax.setText("GST");
        jPanel1.add(txttax, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 70, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 590, 10));

        txttotalinwords.setText("Total in Words:  ");
        jPanel1.add(txttotalinwords, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, -1, -1));

        jLabel24.setText("Total: ");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, -1, -1));

        jLabel25.setText("Total in Words:  ");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel26.setText("Receiver Signature");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, -1, 20));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 210, 10));

        txtremark.setText("Remarks: ");
        jPanel1.add(txtremark, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, -1, -1));

        jLabel27.setText("Remarks: ");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        jLabel28.setText("Total: ");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, -1, -1));

        txttotal.setText("Total: ");
        jPanel1.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 560, 560));

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 80, -1));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 610, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btneditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(153,204,255);
        paneledit.setBackground(clr);
    }//GEN-LAST:event_btneditMouseEntered

    private void btneditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseExited
        // TODO add your handling code here:
        Color clr=new Color(153,255,255);
        paneledit.setBackground(clr);
    }//GEN-LAST:event_btneditMouseExited

    private void paneleditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneleditMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_paneleditMouseEntered

    private void btnhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomeMouseClicked
        // TODO add your handling code here:.
        updatefeedetails up=new updatefeedetails();
        up.show();
        this.dispose();
    }//GEN-LAST:event_btnhomeMouseClicked

    private void btnhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomeMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(153,204,255);
        panelhome.setBackground(clr);
    }//GEN-LAST:event_btnhomeMouseEntered

    private void btnhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomeMouseExited
        // TODO add your handling code here:
        Color clr=new Color(153,255,255);
        panelhome.setBackground(clr);

    }//GEN-LAST:event_btnhomeMouseExited

    private void panelhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelhomeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelhomeMouseEntered

    private void btnsearchrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsearchrecordMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(153,204,255);
        panelsearchrecord.setBackground(clr);
    }//GEN-LAST:event_btnsearchrecordMouseEntered

    private void btnsearchrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsearchrecordMouseExited
        // TODO add your handling code here:
        Color clr=new Color(153,255,255);
        panelsearchrecord.setBackground(clr);
    }//GEN-LAST:event_btnsearchrecordMouseExited

    private void panelsearchrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelsearchrecordMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelsearchrecordMouseEntered

    private void btnviewallMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnviewallMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(153,204,255);
        panelviewall.setBackground(clr);
    }//GEN-LAST:event_btnviewallMouseEntered

    private void btnviewallMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnviewallMouseExited
        // TODO add your handling code here:
        Color clr=new Color(153,255,255);
        panelviewall.setBackground(clr);
    }//GEN-LAST:event_btnviewallMouseExited

    private void panelviewallMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelviewallMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelviewallMouseEntered

    private void btnlogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(153,204,255);
        panellogout.setBackground(clr);
    }//GEN-LAST:event_btnlogoutMouseEntered

    private void btnlogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseExited
        // TODO add your handling code here:
        Color clr=new Color(153,255,255);
        panellogout.setBackground(clr);
    }//GEN-LAST:event_btnlogoutMouseExited

    private void panellogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panellogoutMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_panellogoutMouseEntered

    private void btnbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(153,204,255);
        panelback.setBackground(clr);
    }//GEN-LAST:event_btnbackMouseEntered

    private void btnbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseExited
        // TODO add your handling code here:
        Color clr=new Color(153,255,255);
        panelback.setBackground(clr);
    }//GEN-LAST:event_btnbackMouseExited

    private void panelbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelbackMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelbackMouseEntered

    private void btnhome1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome1MouseClicked
        // TODO add your handling code here:
        home hm=new home();
        hm.show();
        this.dispose();
    }//GEN-LAST:event_btnhome1MouseClicked

    private void btnhome1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome1MouseEntered

    private void btnhome1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome1MouseExited

    private void panelhome1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelhome1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelhome1MouseEntered

    private void btnhome2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome2MouseClicked

    private void btnhome2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome2MouseEntered

    private void btnhome2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome2MouseExited

    private void panelhome2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelhome2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelhome2MouseEntered

    private void btnhome3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome3MouseClicked

    private void btnhome3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome3MouseEntered

    private void btnhome3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome3MouseExited

    private void btnhome4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome4MouseClicked

    private void btnhome4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome4MouseEntered

    private void btnhome4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome4MouseExited

    private void panelhome4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelhome4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelhome4MouseEntered

    private void panelhome3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelhome3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelhome3MouseEntered

    private void btnhome5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome5MouseClicked
        // TODO add your handling code here:
        PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
                jPanel1.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
    }
        }
    }//GEN-LAST:event_btnhome5MouseClicked

    private void btnhome5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome5MouseEntered

    private void btnhome5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome5MouseExited

    private void btnhome6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome6MouseClicked

    private void btnhome6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome6MouseEntered

    private void btnhome6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome6MouseExited

    private void panelhome6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelhome6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelhome6MouseEntered

    private void btnhome7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome7MouseClicked

    private void btnhome7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome7MouseEntered

    private void btnhome7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome7MouseExited

    private void btnhome8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome8MouseClicked

    private void btnhome8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome8MouseEntered

    private void btnhome8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome8MouseExited

    private void panelhome8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelhome8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelhome8MouseEntered

    private void panelhome7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelhome7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelhome7MouseEntered

    private void panelhome5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelhome5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelhome5MouseEntered

    private void btnsearchrecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsearchrecordMouseClicked
        // TODO add your handling code here:
        searchRecord sc=new searchRecord();
        sc.show();
        this.dispose();
    }//GEN-LAST:event_btnsearchrecordMouseClicked

    private void btneditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseClicked
        // TODO add your handling code here:
        editCourse ec=new editCourse();
        ec.show();
        this.dispose();
    }//GEN-LAST:event_btneditMouseClicked

    private void btnviewallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnviewallMouseClicked
        // TODO add your handling code here:
        viewAllRecord var=new viewAllRecord();
        var.show();
        this.dispose();
    }//GEN-LAST:event_btnviewallMouseClicked

    private void btnbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnbackMouseClicked

    private void btnlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseClicked
        // TODO add your handling code here:
        Login lg=new Login();
        lg.show();
        this.dispose();
    }//GEN-LAST:event_btnlogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(printreceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(printreceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(printreceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(printreceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new printreceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnback;
    private javax.swing.JLabel btnedit;
    private javax.swing.JLabel btnhome;
    private javax.swing.JLabel btnhome1;
    private javax.swing.JLabel btnhome2;
    private javax.swing.JLabel btnhome3;
    private javax.swing.JLabel btnhome4;
    private javax.swing.JLabel btnhome5;
    private javax.swing.JLabel btnhome6;
    private javax.swing.JLabel btnhome7;
    private javax.swing.JLabel btnhome8;
    private javax.swing.JLabel btnlogout;
    private javax.swing.JLabel btnsearchrecord;
    private javax.swing.JLabel btnviewall;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblbankname;
    private javax.swing.JLabel lblcdd;
    private javax.swing.JPanel panelback;
    private javax.swing.JPanel paneledit;
    private javax.swing.JPanel panelhome;
    private javax.swing.JPanel panelhome1;
    private javax.swing.JPanel panelhome2;
    private javax.swing.JPanel panelhome3;
    private javax.swing.JPanel panelhome4;
    private javax.swing.JPanel panelhome5;
    private javax.swing.JPanel panelhome6;
    private javax.swing.JPanel panelhome7;
    private javax.swing.JPanel panelhome8;
    private javax.swing.JPanel panellogout;
    private javax.swing.JPanel panelsearchrecord;
    private javax.swing.JPanel panelsidebar;
    private javax.swing.JPanel panelviewall;
    private javax.swing.JLabel txtbankname;
    private javax.swing.JLabel txtchequeddno;
    private javax.swing.JLabel txtdate;
    private javax.swing.JLabel txtgst;
    private javax.swing.JLabel txtinitialamount;
    private javax.swing.JLabel txtpaymentmode;
    private javax.swing.JLabel txtreceiptno;
    private javax.swing.JLabel txtreceivedfrom;
    private javax.swing.JLabel txtremark;
    private javax.swing.JLabel txttax;
    private javax.swing.JLabel txttotal;
    private javax.swing.JLabel txttotalinwords;
    private javax.swing.JLabel txtyear1;
    private javax.swing.JLabel txtyear2;
    // End of variables declaration//GEN-END:variables
}
